name: pet_log
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_fonts: ^2.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/logo.svg
    - lib/assets/google_logo.svg
    - lib/assets/dog_icon.svg

