name: pet_log
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_fonts: ^2.1.0
  flutter:
    sdk: flutter

  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  flutter_svg: ^0.23.0+1
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  google_sign_in: ^5.2.1
  firebase_auth: ^3.2.0
  provider: ^6.0.1
  intl: ^0.17.0
  jiffy: ^4.1.0
  file_picker: ^4.3.0
  path_provider: ^2.0.8
  path: ^1.8.0
  url_launcher: ^6.0.17
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/logo.svg
    - lib/assets/google_logo.svg
    - lib/assets/dog_icon.svg
    - lib/assets/medicine_allergies.svg
    - lib/assets/medicine_analyzes.svg
    - lib/assets/medicine_documents.svg
    - lib/assets/medicine_labtests.svg
    - lib/assets/medicine_surgeries.svg
    - lib/assets/medicine_veterinarian.svg
    - lib/assets/worm_vaccine.svg
    - lib/assets/fur_icon.svg
    - lib/assets/vaccination_icon.svg
    - lib/assets/fleas_and_ticks.svg
    - lib/assets/ears_icon.svg
    - lib/assets/bath_icon.svg
